org: ysaac
app: seek-task
service: seek-task

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  auth:
    handler: handlers/auth_handler.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true
      - http:
          path: auth/login
          method: post
          cors: true

  tasks:
    handler: handlers/task_handler.handler
    events:
      - http:
          path: tasks
          method: post
          cors: true
      - http:
          path: tasks
          method: get
          cors: true
      - http:
          path: tasks/{id}
          method: get
          cors: true
      - http:
          path: tasks/{id}
          method: put
          cors: true
      - http:
          path: tasks/{id}
          method: delete
          cors: true
      - http:
          path: tasks/stats
          method: get
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline

package:
  individually: true
  patterns:
    - "!**/__pycache__/**"
    - "!tests/**"
    - "!*.pyc"
    - "!*.pyo"

