# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ysaac
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: seek-task
# "service" is the name of this project. This will also be added to your AWS resource names.
service: seek-task

provider:
  name: aws
  runtime: python3.10

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

